name: Homebrew

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
    - uses: mislav/bump-homebrew-formula-action@v1
      with:
        formula-name: atcoder
        homebrew-tap: sachaos/homebrew-atcoder
        base-branch: master
      env:
        COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
