name: Release

on:
  push:
    tags:
    - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Unshallow
      run: git fetch --prune --unshallow
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
    - uses: mislav/bump-homebrew-formula-action@v1
      # if: "!contains(github.ref, '-')" # skip prereleases
      with:
        formula-name: atcoder
        homebrew-tap: sachaos/homebrew-atcoder
        base-branch: master
        commit-message: "${{formulaName}} ${{version}}"
      env:
        COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
